url: 'https://dimwanderings.janczak.net'
name: 'Dimitri&#039;s Wanderings'
description: 'Personal and whimsical wanderings mostly about IT'
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
